In [7]:
import numpy as np
arr = np.array((10,12,5))
print(arr)
print(type(arr))

[10 12  5]
<class 'numpy.ndarray'>

In [13]:
arr_1 = np.array([20,24,16,8])
arr_2 = np.array([5,8,2,4])

list_1 = arr_1.tolist()
list_2 = arr_2.tolist()

list_sum = {
    "add": [a + b for a, b in zip(list_1, list_2)],
    "sub": [a - b for a, b in zip(list_1, list_2)],
    "mul": [a * b for a, b in zip(list_1, list_2)],
    "div": [a / b for a, b in zip(list_1, list_2)],
    "mod": [a % b for a, b in zip(list_1, list_2)],
}

print("List mathematical operations: ", list_sum)

print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)
print(arr_1 % arr_2)

List mathematical operations:  {'add': [25, 32, 18, 12], 'sub': [15, 16, 14, 4], 'mul': [100, 192, 32, 32], 'div': [4.0, 3.0, 8.0, 2.0], 'mod': [0, 0, 0, 0]}
[25 32 18 12]
[15 16 14  4]
[100 192  32  32]
[4. 3. 8. 2.]
[0 0 0 0]

In [21]:
arr = np.array([16, 9, 25, 64])

print("Sum:", np.sum(arr))
print("Square roots:", np.sqrt(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

print(arr.dtype)

Sum: 114
Square roots: [4. 3. 5. 8.]
Mean: 28.5
Median: 20.5
Maximum: 64
Minimum: 9
int64

In [23]:
arr = np.array([16, 9, 25, 64], dtype=np.float64)
print(arr)
print(arr.dtype)

[16.  9. 25. 64.]
float64

In [50]:
sample_2D = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(sample_2D)
print(type(sample_2D))
print(sample_2D.shape)
print(sample_2D.size)
print(sample_2D.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)
8
2

In [62]:
arr = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [7,8,9,10]
    ], 
    [
        [10,11,12,13],
        [14,15,16,17],
        [18,19,20,21]
    ]
])
# print(arr.shape)
# print(arr.size)
# print(arr.ndim)

print(arr[1,0,2])
print(arr[-1, -3, -2])

12
12

In [75]:
arr = np.array([101,20,30,15,8])
condition = arr > 15
print(type(condition))
print(condition)

filtered_arr = arr[condition]
print(type(filtered_arr))
print(filtered_arr)

# One line
print(type(arr[arr > 15]))
print(arr[arr > 15])

<class 'numpy.ndarray'>
[ True  True  True False False]
<class 'numpy.ndarray'>
[101  20  30]
<class 'numpy.ndarray'>
[101  20  30]
[20 15]

In [77]:
print(arr[(arr > 10) & (arr < 25)])

[20 15]

In [83]:
sample_arr = np.zeros(5)
print(sample_arr)

[0. 0. 0. 0. 0.]

In [81]:
sample_arr = np.zeros((2,3))
print(sample_arr)

[[0. 0. 0.]
 [0. 0. 0.]]

In [84]:
sample_arr = np.ones((2,3))
print(sample_arr)

[[1. 1. 1.]
 [1. 1. 1.]]

In [89]:
sample_arr = np.full((2,3), fill_value=10)
print(sample_arr)

[[10 10 10]
 [10 10 10]]

In [90]:
sample_arr = np.full((2,3), [1,8,12])
print(sample_arr)

[[ 1  8 12]
 [ 1  8 12]]

In [91]:
sample_arr = np.empty((2,3))
print(sample_arr)

[[5.e-323 5.e-323 5.e-323]
 [5.e-323 5.e-323 5.e-323]]

In [ ]:
import pandas as pd

temperatures = pd.Series([32, 28, 35, 30], name="Temps", index=['Monday', 'Tuesday', 'Wednesday', 'Thursday'])
print(type(temperatures))
print(temperatures)

<class 'pandas.Series'>
Monday       32
Tuesday      28
Wednesday    35
Thursday     30
Name: Temps, dtype: int64

In [103]:
print(temperatures.loc['Wednesday'])
print(temperatures.iloc[2])

35
35

In [111]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Gender': ['F', 'M', 'M']
}

df = pd.DataFrame(data=data, index=[f'student_{val}' for val in range(len(data['Name']))])
print(type(df))
print(df)

<class 'pandas.DataFrame'>
              Name  Age Gender
student_0    Alice   25      F
student_1      Bob   30      M
student_2  Charlie   35      M

In [137]:
print(df.loc['student_1', 'Age'])
print(df.iloc[1, 1])

print("\nStudent 2 Row:")
print(df.loc['student_2'])
print(type(df.loc['student_2']))

print("\nAge Column:")
print(df['Age'])
print(type(df['Age']))

30
30

Student 2 Row:
Name      Charlie
Age            35
Gender          M
Name: student_2, dtype: object
<class 'pandas.Series'>

Age Column:
student_0    25
student_1    30
student_2    35
Name: Age, dtype: int64
<class 'pandas.Series'>

In [138]:
print(df.shape)
print(df.size)
len(df)
print(df.dtypes)

(3, 3)
9
Name        str
Age       int64
Gender      str
dtype: object

In [139]:
column_names = df.columns
print(type(column_names))
print(column_names)

<class 'pandas.Index'>
Index(['Name', 'Age', 'Gender'], dtype='str')

In [140]:
print(list(column_names))

['Name', 'Age', 'Gender']

In [144]:
print(type(df.values))
print(df.values)

<class 'numpy.ndarray'>
[['Alice' 25 'F']
 ['Bob' 30 'M']
 ['Charlie' 35 'M']]

In [145]:
df

              Name  Age Gender
student_0    Alice   25      F
student_1      Bob   30      M
student_2  Charlie   35      M

In [189]:
data = {
    'Age': [25,30,35,40],
    'Salary': [50000,60000,70000,80000]
}

df = pd.DataFrame(data=data)
df

   Age  Salary
0   25   50000
1   30   60000
2   35   70000
3   40   80000

In [184]:
# df.sum()
# df.mean()
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000

In [185]:
filtered_df = df[df['Age'] > 25]
filtered_df

   Age  Salary
1   30   60000
2   35   70000
3   40   80000

In [234]:
data = {
    'Age': [25,30,35,40],
    'Salary': [50000,60000,70000,80000]
}

df = pd.DataFrame(data=data)
new_filtered_data = df[(df['Age'] > 30) & (df['Salary'] > 75000)]
new_filtered_data

   Age  Salary
3   40   80000

In [198]:
sorted_df = df.sort_values(by="Age")
print(type(sorted_df))
sorted_df

<class 'pandas.DataFrame'>

   Age  Salary
0   25   50000
1   30   60000
2   35   70000
3   40   80000

i. Add a new col called 'Distance'
ii. values -> 8, 4, 20, 17
iii. [38,78000, 15]

In [235]:
df['Distance'] = [8,4,20,17]
df.loc[len(df)] = [38,78000, 15]
print(len(df))
df

5

   Age  Salary  Distance
0   25   50000         8
1   30   60000         4
2   35   70000        20
3   40   80000        17
4   38   78000        15

In [236]:
print(df.drop('Distance',axis=1,inplace=True))
df

None

   Age  Salary
0   25   50000
1   30   60000
2   35   70000
3   40   80000
4   38   78000

In [241]:
df = pd.read_csv('sample.csv')
df
# type(df) pandas.DataFrame
# df.head()

    id           name  age           city  salary
0    1  Alice Johnson   28       New York   55000
1    2      Bob Smith   34    Los Angeles   62000
2    3  Charlie Brown   45        Chicago   78000
3    4   Diana Prince   29        Houston   59000
4    5     Ethan Hunt   38        Phoenix   71000
5    6    Fiona Apple   26   Philadelphia   52000
6    7  George Miller   52    San Antonio   85000
7    8     Hannah Lee   31      San Diego   64000
8    9     Ian Wright   40         Dallas   73000
9   10  Julia Roberts   35       San Jose   68000
10  11     Kevin Hart   33         Austin   66000
11  12   Laura Palmer   27   Jacksonville   54000
12  13  Michael Scott   48     Fort Worth   82000
13  14    Nina Simone   30       Columbus   61000
14  15    Oscar Wilde   42      Charlotte   75000
15  16    Paula Abdul   36  San Francisco   69000
16  17   Quincy Jones   55   Indianapolis   90000
17  18   Rachel Green   32        Seattle   67000
18  19   Steve Rogers   41         Denver   74000
19  20    Tina Turner   39     Washington   72000

In [242]:
df.drop(labels='id', axis=1)

             name  age           city  salary
0   Alice Johnson   28       New York   55000
1       Bob Smith   34    Los Angeles   62000
2   Charlie Brown   45        Chicago   78000
3    Diana Prince   29        Houston   59000
4      Ethan Hunt   38        Phoenix   71000
5     Fiona Apple   26   Philadelphia   52000
6   George Miller   52    San Antonio   85000
7      Hannah Lee   31      San Diego   64000
8      Ian Wright   40         Dallas   73000
9   Julia Roberts   35       San Jose   68000
10     Kevin Hart   33         Austin   66000
11   Laura Palmer   27   Jacksonville   54000
12  Michael Scott   48     Fort Worth   82000
13    Nina Simone   30       Columbus   61000
14    Oscar Wilde   42      Charlotte   75000
15    Paula Abdul   36  San Francisco   69000
16   Quincy Jones   55   Indianapolis   90000
17   Rachel Green   32        Seattle   67000
18   Steve Rogers   41         Denver   74000
19    Tina Turner   39     Washington   72000